

var resources = [
  {
    solutionId:'0001',
    label:'sleep',
    labels:['sleep','exercise'],
    genderTag:'male',
    ageTag:'18-24',
    platform:'iOS',
    title:'Sleepio',
    price:'FREE',
    categ:'App',
    description:'Improve your sleep with proven techniques developed over 35 years of research',
    imgURL:'https://firebasestorage.googleapis.com/v0/b/website-973e0.appspot.com/o/images%2FSpleepio-logo-2016.png?alt=media&token=1feb215a-52cf-434a-8f25-16482412259f',
    website:'https://www.sleepio.com',
    comments:'B: "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
  },
    {
    label:'loneliness',
    title:'Me 3',
    price:'2.4$',
    categ:'Activity',
    description:'We make epic human connections for the purposes of friendship in groups of 3.',
    imgURL:'https://firebasestorage.googleapis.com/v0/b/website-973e0.appspot.com/o/images%2FWe3_App_Icon.png?alt=media&token=e01af238-d8ea-48db-8874-840b2abdbc32',
    website:'https://www.we3app.com/',
    comments:'B: "Me 3 is a good way to meet new people, it has created a lot of great connections already..."'
  },
  {
    label:'exercise',
    title:'Couch to 5K',
    price:'FREE',
    categ:'App',
    imgURL:'https://firebasestorage.googleapis.com/v0/b/website-973e0.appspot.com/o/images%2Fcouch25k.jpeg?alt=media&token=e71d69d5-9740-4560-b7b8-5d7612a3f234',
    description:'Getting you off the couch and running in just than 9 weeks',
    website:'https://www.nhs.uk/LiveWell/c25k/Pages/couch-to-5k.aspx',
    comments:'B: "Running! Sometimes getting out and run can be a hard decision, but this app knows how to make the first step..."'
  },
  {
    label:'purpose',
    title:'Live Happy',
    price:'FREE',
    categ:'Podcast',
    description:'The editors of Live Happy magazine bring you ideas on how to live a happier and more meaningful life',
    imgURL:'https://firebasestorage.googleapis.com/v0/b/website-973e0.appspot.com/o/images%2FliveNow.jpg?alt=media&token=ec5634ea-7f7b-44eb-b5f2-482193bc8e06',
    website:'https://www.livehappy.com/podcast',
    comments:'B: "Want to hear great suggestions through a podcast? We do not need a lot sometimes to be a little happier..."'
  },
    {
      label:'nutrition',
      title:'MyFitnessPal',
      price:'FREE',
      categ:'App',
      description:'Free online calorie counter and diet plan. Lose weight by tracking your caloric intake quickly and easily.',
      imgURL:'https://firebasestorage.googleapis.com/v0/b/website-973e0.appspot.com/o/images%2Fmyfitpal.jpeg?alt=media&token=21dfdcb0-5f22-40c1-bda6-14b96618bb7c',
      website:'https://www.myfitnesspal.com',
      comments:'B: "Eating better needs consistency and MyFitnessPal is a great app to get clarity in food!"'
  },
  {
    solutionId:'0001',
    label:'sleep',
    labels:['sleep','stress'],
    genderTag:['male','female','other'],
    ageTag:['18-24','25-34','35-44','45-54','55-64','65+'],
    platform:['iOS','Android'],
    title:'Sleepio',
    price:'Relevant Free',
    categ:'App',
    description:'Sleepio helps you improve your sleep with proven techniques developed over 35 years of research',
    imgURL:'https://firebasestorage.googleapis.com/v0/b/website-973e0.appspot.com/o/images%2FSpleepio-logo-2016.png?alt=media&token=1feb215a-52cf-434a-8f25-16482412259f',
    website:'https://www.sleepio.com',
    comments:' "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
  },
{
    solutionId:'0002',
    label:'sleep',
    labels:['sleep'],
    genderTag:['male','female','other'],
    ageTag:['18-24','25-34','35-44','45-54','55-64','65+'],
    platform:['iOS' , 'Android'],
    title:'Sleep Better',
    price:'Relevant Free',
    categ:'App',
    description:' The Sleep Better sleep cycle alarm clock app lets you track your sleep, monitor your dreams and improve your bedtime habits',
    imgURL:'https://www.spoofee.com/images/dealofday/original/915351.jpg',
    website:' https://www.runtastic.com/en/apps/sleepbetter',
    comments:'B: "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
  },
{
    solutionId:'0003',
    label:'sleep',
    labels:['sleep'],
    genderTag:['male','female','other'],
    ageTag:['18-24','25-34','35-44','45-54','55-64','65+'],
    platform:['iOS' , 'Android'],
    title:'Sleep Genius',
    price:'$4.99',
    categ:'App',
    description:' The Sleep Genius Relaxation Program was scientifically¬ created to reduce stress and anxiety by calming both the mind and the body.',
    imgURL:'http://sleepgenius.com/universe/wp-content/uploads/2014/04/app-icon.png',
    website:' http://sleepgenius.com/',
    comments:'B: "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
  },
{
    solutionId:'0004',
    label:'sleep',
    labels:['sleep', 'stress' , 'occupation' , 'nutrition'],
    genderTag:['male', 'female', 'other'],
    ageTag:['18-24','25-34','35-44','45-54','55-64','65+'],
    platform:['iOS'],
    title:'Meditation Studio',
    price:'Relevant Free',
    categ:'App',
    description:'The mind is complicated, but meditation does not have to be. Welcome to Meditation Studio. We make meditation simple.',
    alternativeDescription: 'Whether you want to reduce stress, ease anxiety, improve sleep or boost confidence, we have got meditations for you!',
    imgURL:'https://i1.sndcdn.com/avatars-000278434986-sgsfu7-t500x500.jpg',
    alternativeImg:' http://img.wennermedia.com/620-width/mj-618_348_meditation-studio-meditation-apps-that-work.jpg',
    website:' https://www.meditationstudioapp.com/',
    comments:'B: "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
  },
{
    solutionId:'0005',
    label:'sleep',
    labels:['sleep','anxiety','stress'],
    genderTag:['male','female','other'],
    ageTag:[ '<18','18-24'],
    platform:['iOS','Android'],
    title:'Mindshift',
    price:' Free',
    categ:'App',
    description:' Think of MindShift™ as your portable coach helping you face challenging situations and take charge of your life.',
alternativeDescription: ' MindShift™ will help you learn how to relax, develop more helpful ways of thinking, and identify active steps that will help you take charge of your anxiety.',
    imgURL:'https://lh3.ggpht.com/S3A1v4uapjyVVNmta-OUDQ63EG0q6FZKVNJNbZzWKFzevdxLODoLbBE64ctxs3xiJw=s180',
alternativeImg: ' https://www.sharonselby.com/wp-content/uploads/2013/07/Screen-Shot-2015-11-07-at-5.44.23-PM.png',
    website:' https://www.anxietybc.com/resources/mindshift-app',

    comments:'B: "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
  },

{
    solutionId:'0006',
    label:'sleep',
    labels:['sleep','stress'],
    genderTag:['male','female','other'],
    ageTag: ['18-24','25-34','35-44','45-54','55-64','65+'],
    platform:['iOS','Android'],
    title:'Brain.fm',
    price:'Relevant Free',
    categ:'App',
    description:'Music for brain stimulation – focus, meditation, relaxation, sleep. Unlock music is potential to influence cognative states',
    imgURL: 'https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/1d/7e/69/1d7e692c-bff1-f656-38cc-caf2136a9ef5/mzl.tiupyrjx.png/246x0w.jpg',
    alternativeImg: ' http://www.stashq.com/wp-content/uploads/2017/01/logo-brainfm.png',
    website:' https://www1.brain.fm/app',

    comments:'B: "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
  },
{
    solutionId:'0007',
    label:'sleep',
    labels:['sleep','stress'],
    genderTag:['male','female','other'],
    ageTag: ['18-24','25-34','35-44','45-54','55-64','65+'],
    platform:['iOS' , 'Android'],
    title:'Calm',
    price:'Relevant Free',
    categ:'App',
    description:'We help people to relax, meditate and sleep. Our mission is to make the world happier and healthier.',
    imgURL: 'https://images-na.ssl-images-amazon.com/images/I/71DP3hD7K8L.png',
    website:' https://www.calm.com/',
 comments:'B: "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
},
{
    solutionId:'0008',
    label:'sleep',
    labels:['sleep','stress'],
    genderTag:['male','female','other'],
    ageTag: ['<18','18-24','25-34','35-44','45-54','55-64','65+'],
    platform:['iOS' , 'Android'],
    title:'Noisli',
    price:'£1.99',
    categ:'App',
    description:'Improve focus and boost your productivity. Mix different sounds and create your perfect environment.',
    imgURL: 'https://dl1.cbsistatic.com/i/2016/07/03/ead00803-7826-4a90-9f57-6851749e8848/aa5c8e6ace3460da2a4a3ca55694a656/imgingest-399061660629536481.png',
    website:'https://www.noisli.com/',
    comments:'B: "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
  },
{
    solutionId:'0009',
    label:'sleep',
    labels:['sleep','stress'],
    genderTag:['male','female','other'],
    ageTag: ['<18','18-24','25-34','35-44','45-54','55-64','65+'],
    platform:['iOS' , 'Android'],
    title:'pzizz- deep sleep & power nap',
    price:'Relevant Free',
    categ:'App',
    description:'Sleep at the push of a button! The worlds most advanced sleep and power nap system to fall asleep fast, stay asleep, and wake up feeling refreshed.',
    imgURL:'https://cdnp1.stackassets.com/4948f3dabddde6602a2768666dd7f866544c9392/store/opt/596/447/cad1458b42b2bab1418e05d76fa5c7decf4dd22c8f782caacd286c1b1689/product_21656_product_shots1_image.jpg',
    alternativeImg: 'http://is5.mzstatic.com/image/thumb/Purple128/v4/d4/da/09/d4da09e5-70da-10e3-4283-972e3b0caad5/source/175x175bb.jpg',
    website:'https://pzizz.com/',
    comments:'B: "This app has worked to improve sleep for people similar to you, I hope you do not mind the professor!"'
  }


]

export default resources;
